### ISSUE TITLE
Issue APK Builder - In Linux 

### ISSUE THREAD

**Issue by seervisolution** [ExtremeHacking/infinityhacks-botnet#5]
When i Try to Build Its Giving me this Error.
![Screenshot_2020-05-07_19-36-05](https://user-images.githubusercontent.com/64315140/81310214-70832a00-90a1-11ea-9a3f-2c5ec3269f32.png)

![Screenshot_2020-05-07_19-36-05](https://user-images.githubusercontent.com/64315140/81310281-87298100-90a1-11ea-9d04-f86df986ac77.png)

and buffering Finalizing

Help me out 

5/7/2020, 2:52:03 PM => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/home/urnotsecure/Downloads/bootnet/infinityhacks-botnet-master/app/factory/sign.jar" "/home/urnotsecure/Downloads/bootnet/infinityhacks-botnet-master/assets/webpublic/build.apk" Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ... 3 more

**Comment by someshsrichandan** [comment]
Install java (jdk ,jre) properly on your linux
